[package]
name = "kata-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Lowering TAST→CLIF + MetadataTable sidecar + emit Cranelift JIT"

[dependencies]
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-native.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
cranelift-object.workspace = true
kata-core.workspace = true
kata-ast.workspace = true
kata-inference.workspace = true
kata-rt.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
kata-lexer.workspace = true
kata-parser.workspace = true
kata-resolution.workspace = true
kata-optimizer.workspace = true