[package]
name = "kata-driver"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "CLI do compilador Kata — orquestra o pipeline completo"
build = "build.rs"

[[bin]]
name = "kata"
path = "src/main.rs"

[dependencies]
clap.workspace = true
miette.workspace = true
kata-lexer.workspace = true
kata-parser.workspace = true
kata-resolution.workspace = true
kata-inference.workspace = true
kata-codegen.workspace = true
kata-monomorph.workspace = true
kata-optimizer.workspace = true
kata-tree-shaking.workspace = true
kata-comptime.workspace = true
kata-core.workspace = true
kata-ast.workspace = true
kata-diagnostics.workspace = true
kata-rt.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
rustyline.workspace = true
kata-lsp.workspace = true
tower-lsp.workspace = true
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
insta.workspace = true