use std::fmt;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum Token {
    InterfaceID(String),
    TypeID(String),
    Ident(String),
    ActionIdent(String),
    TypeVar(String),
    String(String),
    Int(String),
    Float(String),
    Indent,
    Dedent,
    Newline,

    // Keywords
    Data,
    Enum,
    Interface,
    Implements,
    Export,
    Import,
    Lambda,
    Action,
    Match,
    Loop,
    For,
    In,
    Let,
    Var,
    Break,
    Continue,
    With,
    As,
    Otherwise,
    Alias,
    Select,
    Case,
    Timeout,

    // Punctuation
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Pipe,
    RightPipe,
    Colon,
    DoubleColon,
    Arrow,
    FatArrow,
    Hole,
    Dollar,
    Dot,
    Ellipsis,
    Question,
    Semicolon,
    Comma,
    Ampersand,
    ChannelSend,
    ChannelRecv,
    ChannelRecvNonBlock,

    Directive(String),
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::InterfaceID(s) => write!(f, "{}", s),
            Token::TypeID(s) => write!(f, "{}", s),
            Token::Ident(s) => write!(f, "{}", s),
            Token::ActionIdent(s) => write!(f, "{}!", s),
            Token::TypeVar(s) => write!(f, "{}", s),
            Token::String(s) => write!(f, "\"{}\"", s),
            Token::Int(i) => write!(f, "{}", i),
            Token::Float(fl) => write!(f, "{}", fl),
            Token::Indent => write!(f, "<INDENT>"),
            Token::Dedent => write!(f, "<DEDENT>"),
            Token::Newline => write!(f, "<NEWLINE>"),

            Token::Data => write!(f, "data"),
            Token::Enum => write!(f, "enum"),
            Token::Interface => write!(f, "interface"),
            Token::Implements => write!(f, "implements"),
            Token::Export => write!(f, "export"),
            Token::Import => write!(f, "import"),
            Token::Lambda => write!(f, "lambda"),
            Token::Action => write!(f, "action"),
            Token::Match => write!(f, "match"),
            Token::Loop => write!(f, "loop"),
            Token::For => write!(f, "for"),
            Token::In => write!(f, "in"),
            Token::Let => write!(f, "let"),
            Token::Var => write!(f, "var"),
            Token::Break => write!(f, "break"),
            Token::Continue => write!(f, "continue"),
            Token::With => write!(f, "with"),
            Token::As => write!(f, "as"),
            Token::Otherwise => write!(f, "otherwise"),
            Token::Alias => write!(f, "alias"),
            Token::Select => write!(f, "select"),
            Token::Case => write!(f, "case"),
            Token::Timeout => write!(f, "timeout"),

            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::LBracket => write!(f, "["),
            Token::RBracket => write!(f, "]"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::RightPipe => write!(f, "|>"),
            Token::Pipe => write!(f, "|"),
            Token::Colon => write!(f, ":"),
            Token::DoubleColon => write!(f, "::"),
            Token::Arrow => write!(f, "->"),
            Token::FatArrow => write!(f, "=>"),
            Token::Hole => write!(f, "_"),
            Token::Dollar => write!(f, "$"),
            Token::Dot => write!(f, "."),
            Token::Ellipsis => write!(f, "..."),
            Token::Question => write!(f, "?"),
            Token::Semicolon => write!(f, ";"),
            Token::Comma => write!(f, ","),
            Token::Ampersand => write!(f, "&"),
            Token::ChannelSend => write!(f, "!>"),
            Token::ChannelRecv => write!(f, "<!"),
            Token::ChannelRecvNonBlock => write!(f, "<!?"),
            Token::Directive(s) => write!(f, "@{}", s),
        }
    }
}
