[package]
name = "kata-comptime"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Comptime pass — avaliação em compile-time via JIT-and-execute"

[dependencies]
kata-core.workspace = true
kata-ast.workspace = true
kata-inference.workspace = true
kata-codegen.workspace = true
kata-rt.workspace = true
thiserror.workspace = true
miette.workspace = true